version: '3.1'

services:

  # La base de données PostgreSQL. Elle est configurée de façon à être joignable sur
  # localhost:5432 .
  #
  # Utilisateur: becode
  # Mot de passe: becode
  # Base de données par défault: becode

  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - dbvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lcantini
      POSTGRES_PASSWORD: lcantini
      POSTGRES_DB: dbBrite
  adminer:
    image: adminer:4.7
    depends_on:
      - db
    ports:
      - "9000:8080"
volumes:
  dbvolume:
